services:
  app:
    build: .
    container_name: projetoestudolaravel-app
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    networks:
      - minha-rede

  db:
    image: mysql:8.0
    container_name: meu-mysql-server
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - dados-mysql:/var/lib/mysql
    networks:
      - minha-rede

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: meu-gerenciador-db
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      - "8081:80"
    networks:
      - minha-rede

networks:
  minha-rede:
    driver: bridge

volumes:
  dados-mysql: